### ISSUE TITLE
Making Value subtype Number, and Tensor subtype AbstractArray

### ISSUE THREAD

**Issue by oxinabox** [mikesaint-antoine/SimpleGrad.jl#3]
Is suggested that  Value should subtype Number ,(or perhaps Real) and Tensor should subtype AbstractArray

This is what is done in Tracker.jl and ReversedDiff.jl with there equivalent types.
In both cases (iirc) called TrackedReal and TrackedMatrix.

This will allow it to pass through type constraints, making it much easier to compose through existing code.

We did not do this in Nabla.jl, and had just one type for both (Node) and it was incredibly frustrating.

**Comment by mikesaint-antoine** [comment]
Ok I'll work on that and add it to the next version, thanks!

**Comment by mikesaint-antoine** [comment]
Hi @oxinabox, sorry about the late response! 

Ok, I might have spoke too soon about adding the subtyping, because now I'm actually having second thoughts and was hoping to maybe pick your brain about it, because it’s possible that I might just be making a beginner mistake. 

This is the code that I was testing out, for the Value subtyping:

```julia
mutable struct Value{opType} <: Number
    data::Float64
    grad::Float64
    op::opType
end

import Base.==
function ==(a::Value, b::Value)
    return a.data == b.data && a.grad == b.grad && a.op == b.op
end


Base.promote_rule(::Type{Value}, ::Type{T}) where {T<:Number} = Value
Base.convert(::Type{Value}, x::Number) = Value(x)
```

I thought that an advantage of this would be that it would let me do operations like Value + Number and Number + Value and handle the type conversion of Number -> Value automatically, without me needing to define `+(a::Value, b::Number)` and `+(a::Number, b::Value)` explicitly. However, it doesn't seem to be working. When I try it, I get this error:

`ERROR: LoadError: promotion of types Value{Nothing} and Int64 failed to change any arguments`

Do you know if I'm making some obvious mistake here? I think the issue might be something with the Value type parameters, but can't figure it out.

Besides automatic type-casting, I originally thought that another advantage of subtyping would be that it would make the Values and Tensors more robust and usable, since they'd be able to pass into functions expecting Number or AbstractArray inputs. But now that I think about it, that actually seems more like a potential problem than an advantage. The whole idea with these objects is that you should be able to do operations on them and then call a backward pass to automatically get the gradients of everything. So if the user tries a forward operation on a Value/Tensor that doesn't have a corresponding backward pass written for it, then it SHOULD throw an error. So now I'm a bit worried that if they're subtyped as Number/AbstractArray that could lead to them seeming to work for forward operations that don't have a corresponding backward pass.

Does that make sense? Anyway sorry if any of these are dumb questions, I'm still a beginner with Julia. Thanks!

**Comment by oxinabox** [comment]
So as long as the basic operations define in you thing have a corresponding backwards pass,
more complex operations defined in terms of them can have the backwards pass defined automatically.
That is the principle of automatic differentation.
And conversely, if they don't you will get an error because it will hit some basic operation during the forward pass that you haven't provided an overload for and thus haven't set up the backwards pass for.
So you are all got there.


Re why the above didn't work.
It is that you need to be a bit more careful around parametric types and `Type` 

the following works

```julia
mutable struct Value{opType} <: Number
    data::Float64
    grad::Float64
    op::opType
end
Value(x::Number) = Value(Float64(x), 0.0, nothing)
Value(x::Value) = x

import Base.==
function ==(a::Value, b::Value)
    return a.data == b.data && a.grad == b.grad && a.op == b.op
end


Base.convert(::Type{Value}, x::Number) = Value(x)

Base.promote_rule(::Type{<:Value}, ::Type{<:Value}) = Value
Base.promote_rule(::Type{<:Value}, ::Type{T}) where {T<:Number} = Value


Operation(args...) = nothing   #placeholder for demo

function Base.:+(a::Value, b::Value)
    out = a.data + b.data

    # Value(data, grad, op)
    result = Value(out, 0.0, Operation(+, (a, b) ))

    return result
end

Value(1.1) + 1.0
```

**Comment by mikesaint-antoine** [comment]
Ah I see, thanks! Ok I will work on adding this to the next version.

**Comment by mikesaint-antoine** [comment]
@oxinabox ok I've rewritten the source code to include the subtyping, and also updated the documentation to reflect these changes. So this will be available with the next version of the package. Thanks a lot for your help with this! 🙂
